TeamFyraSidor/Models/ElPrice.cs
using System.ComponentModel.DataAnnotations;

namespace TeamFyraSidor.Models
{
    public class ElPrice
    {
      
        public required string date { get; set; }
        public required SECategory[] SE1 { get; set; }
        public required SECategory[] SE2 { get; set; }
        public required SECategory[] SE3 { get; set; }
        public required SECategory[] SE4 { get; set; }

        public class SECategory
        {
            public int hour { get; set; }
            public float price_eur { get; set; }
            public float price_sek { get; set; }
            public int kmeans { get; set; }
        }


    }
}

TeamFyraSidor/Controllers/HomeController.cs
using Azure;
using Azure.AI.TextAnalytics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Diagnostics;
using System.Linq;
using TeamFyraSidor.Data;
using TeamFyraSidor.Models;
using TeamFyraSidor.Models.ViewModels;
using TeamFyraSidor.Service;

namespace TeamFyraSidor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArticleService _articleService;
        private readonly IElpriceService _elpriceService;
        private readonly string _endPoint;
        private readonly string _apiKey;

        public HomeController(ILogger<HomeController> logger, IArticleService articleService,  
            IElpriceService elpriceService,IConfiguration configuration)
        {
            _logger = logger;
            _articleService = articleService;
            _elpriceService = elpriceService;
            _endPoint = configuration["LanguageAI:EndPoint"];
            _apiKey = configuration["LanguageAI:ApiKey"];
        }
        
        public IActionResult Index()
        {
            var articles = _articleService.GetHomePages();

            var model = new HomePageVM();

            model.MostPopular = articles.OrderByDescending(a => a.Views).ToList();

            model.Latest = articles.OrderByDescending(x => x.DateStamp).ToList();

            model.EditorChoice = articles.OrderByDescending(a => a.Likes).ThenBy(a => a.Views).Where(a => a.EditorsChoise == true).ToList();

            return View(model);
        }
        [HttpGet]
        public IActionResult LanguageAI()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LanguageAI(string text)
        {
            if (string.IsNullOrEmpty(text))
            {
                ViewBag.Error = "Text cannot be empty.";
                return View();
            }

            var client = new TextAnalyticsClient(new Uri(_endPoint), new AzureKeyCredential(_apiKey));
            DocumentSentiment response = client.AnalyzeSentiment(text); // Analyze sentiment and get response

            if (response == null)
            {
                ViewBag.Error = "Could not analyze sentiment.";
                return View();
            }

            // Pass data to the ViewBag
            ViewBag.Sentiment = response.Sentiment.ToString();
            ViewBag.ConfidenceScores = response.ConfidenceScores;

            return View();
        }

        public IActionResult Privacy()
        {
            var articles = _articleService.GetArticles().ToList();
            return View(articles);
        }

        public IActionResult CookiePolicy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Local()
        {
            var articles = _articleService.GetArticlesByCategoryId(11).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;

            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }

        public IActionResult Sweden()
        {
            var articles = _articleService.GetArticlesByCategoryId(12).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;

            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }

        public IActionResult World()
        {
            var articles = _articleService.GetArticlesByCategoryId(7).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;

            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }

        public IActionResult Travel()
        {
            var articles = _articleService.GetArticlesByCategoryId(9).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;
                      
            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }

        public IActionResult Economy()
        {
            var articles = _articleService.GetArticlesByCategoryId(10).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;

            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }

        public IActionResult Sports()
        {
            var articles = _articleService.GetArticlesByCategoryId(8).OrderByDescending(a => a.DateStamp);

            var model = new CategoryPageVM();
            model.TopArticle = articles.FirstOrDefault()!;

            var others = articles.Skip(1).OrderByDescending(a => a.Views);

            model.Pop3Articles = others.Take(3).ToList();

            model.LatestArticles = others.Skip(3).OrderByDescending(a => a.DateStamp).ToList();

            return View(model);
        }


        public async Task<IActionResult> Search(string searchString)
        {
            var articles = _articleService.GetSearchResult(searchString);
            return View(await articles.ToListAsync());
        }

        public async Task<IActionResult> GetElPriceTodayData()
        {
            var data = await _elpriceService.GetElPriceTodayAsync();
            return Json(data);
        }

        public IActionResult BuySubscription()
        {
            return View();
        }


    }
} 

TeamFyraSidor/ViewComponents/StockViewComponent.cs
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using TeamFyraSidor.Models;
using TeamFyraSidor.Service;

namespace TeamFyraSidor.ViewComponents
{
    public class StockViewComponent : ViewComponent
    {
        private readonly IStockService _stockService;

        public StockViewComponent(IStockService stockService)
        {
            _stockService = stockService;
        }

        public async Task <IViewComponentResult> InvokeAsync(string symbol)
        {
            try
            {
                var stockResponse = await _stockService.GetStockResponseAsync(symbol);

                var stockViewModel = new StockViewModel
                {
                    Symbol = stockResponse.Symbol,
                    Open = stockResponse.Open,
                    High = stockResponse.High
                    //Change = stockResponse.Change,
                    //ChangePercent = stockResponse.ChangePercent
                };

                return View(stockViewModel);
            }
            catch (Exception ex)
            {
                ViewData["Error"] = $"Error: {ex.Message}";
                return View("Error");
            }
           
        }

    }
}

TeamFyraSidor/ViewComponents/WeatherViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using TeamFyraSidor.Models;
using TeamFyraSidor.Service;


namespace TeamFyraSidor.ViewComponents
{
    public class WeatherViewComponent : ViewComponent
    {
        private readonly IWeatherService _weatherService;

        public WeatherViewComponent(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }

        public async Task<IViewComponentResult> InvokeAsync(string city = "Linköping") 
        {
           
            
                try
                {
                    var weather = await _weatherService.GetWeatherAsync(city);

                    var viewModel = new WeatherViewModel
                    {
                        Name = weather.Name,
                        Temp = weather.Main.Temp,
                        Humidity = weather.Main.Humidity,
                        WindSpeed = weather.Wind.Speed,
                        Icon = $"http://openweathermap.org/img/wn/{ weather.Weather.FirstOrDefault()?.Icon}.png" ?? "Icon Not Found",
                        Description = weather.Weather.FirstOrDefault()?.Description ?? "Description Not Found."
                    };

                    return View(viewModel);
                }
                catch (Exception ex)
                {

                    ViewData["Error"] = $"Error: {ex.Message}";
                    return View();
                }

            
           
        }


    }
}

TeamFyraSidor/Views/Home/BuySubscription.cshtml
@using Microsoft.AspNetCore.Identity
@using TeamFyraSidor.Data
@inject SignInManager<User> SignInManager


<div class="bg-body-secondary rounded-3 mt-5">
    @if (User.Identity.IsAuthenticated)
    {
        <p class="text-center fw-bold mt-3">
            Hi, you are logged in!
        </p>
    }
    else
    {
        <div class="text-center mt-3">
            <span>
                Already a subscriber?
            </span>
            <a asp-area="Identity" asp-page="/Account/Login" style="color:blue">Log in here</a>
        </div>
    }

    <h3 class="text-center text-danger pt-3">
        Buy subscription to unlock our articles at Fyra Sidor!
    </h3>
    <p class="text-center fw-bold">
        Join now and continue reading the news <br />
        Choose a plan below to get started!
    </p>

    <div class="p-3">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center bg-info text-white">Sports Monthly</h3>
                        <ul class="list-group fw-semibold">
                            <li class="list-group-item">Unlock every sports article</li>
                            <li class="list-group-item">Renews at 49 Kr per month</li>
                            <li class="list-group-item">Cancel anytime</li>
                        </ul>
                        <div class="d-flex justify-content-center m-3">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Manage/ManageSubscription">Pay 49Kr</a>
                            }
                            else
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Login">Pay 49Kr</a>
                            }

                        </div>
                    </div>
                </div>

            </div>

            <div class="col-md-4">
                <div class="card">

                    <div class="card-body">
                        <h3 class="card-title text-center bg-info text-white">News Monthly</h3>
                        <ul class="list-group fw-semibold">
                            <li class="list-group-item">Unlock every news article except sports</li>
                            <li class="list-group-item">Renews at 99 Kr per month</li>
                            <li class="list-group-item">Cancel anytime</li>
                        </ul>
                        <div class="d-flex justify-content-center m-3">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Manage/ManageSubscription">Pay 99Kr</a>
                            }
                            else
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Login">Pay 99Kr</a>
                            }
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-md-4">
                <div class="card">

                    <div class="card-body ">
                        <h3 class="card-title text-center bg-info text-white">News Plus Monthly</h3>
                        <ul class="list-group fw-semibold">
                            <li class="list-group-item">Unlock every news article</li>
                            <li class="list-group-item">Renews at 139 Kr per month</li>
                            <li class="list-group-item">Cancel anytime</li>
                        </ul>
                        <div class="d-flex justify-content-center m-3">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Manage/ManageSubscription">Pay 139Kr</a>
                            }
                            else
                            {
                                <a class="btn btn-success" asp-area="Identity" asp-page="/Account/Login">Pay 139Kr</a>
                            }
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>

TeamFyraSidor/Views/Home/CookiePolicy.cshtml
<h2>Cookie Policy</h2>

<p>Effective Date: from 2024-12-01</p>

<p>Welcome to Fyra Sidor! This Cookie Policy explains how we use cookies and similar technologies on our website.</p>

<h3>What Are Cookies?</h3>
Cookies are small text files placed on your device (computer, tablet, or smartphone) when you visit a website. Cookies help websites function efficiently, enhance user experience, and provide useful information to website operators.

<h3>Why We Use Cookies</h3>
<h4>We use cookies to:</h4>
Improve the functionality and performance of our website.
Remember your preferences (e.g., language, font size).
Analyze website traffic and user behavior.
Provide personalized content and advertisements.

<h3>
    Types of Cookies We Use
</h3>

<h4>Essential Cookies</h4>


These cookies are necessary for the website to function correctly.
Without them, you may not be able to use certain features of the website.
Performance and Analytics Cookies
These cookies help us understand how visitors interact with our site by collecting anonymous data.
Examples: Google Analytics.

<h4>Functional Cookies</h4>

These cookies remember your preferences to provide you with a more personalized experience.
<h4>Advertising Cookies</h4>

These cookies track your online activity to deliver targeted advertisements based on your interests.
<h3>How to Manage Cookies</h3>
You can control and manage cookies in the following ways:

Most web browsers allow you to block or delete cookies through browser settings.
You can choose to accept or decline cookies when visiting our site.
<p>Note: Disabling cookies may impact the functionality of the website.</p>
Third-Party Cookies
We may allow third-party services to set cookies on your device. These cookies are managed by third parties and are subject to their privacy policies. Examples include:

Google Analytics for traffic analysis.
Advertising partners for personalized ads.
Your Consent
By using our website, you consent to the use of cookies as described in this Cookie Policy. If you do not agree, please disable cookies through your browser settings or refrain from using our website.

Updates to This Policy
We may update this Cookie Policy from time to time. Changes will be posted on this page, and the "Effective Date" will be updated.

<h3>Contact Us</h3>
If you have any questions about this Cookie Policy, please contact us.

TeamFyraSidor/Views/Home/Economy.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "Economy";
}

<h4 class="mt-3">ECONOMY NEWS</h4>
<hr />

<partial name="_CategoryPartial" model="@Model" />

TeamFyraSidor/Views/Home/Elprice.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

TeamFyraSidor/Views/Home/Index.cshtml
@model TeamFyraSidor.Models.ViewModels.HomePageVM
@{
    ViewData["Title"] = "Fyra Sidor";
}

<div class="container-fluid mb-5">
    <div class="section1">
        <div class="row gy-4">

            <h4 class="mt-5 text-danger">LATEST NEWS</h4>
            <hr />
            <div class="col-lg-3 col-md-6 rounded-2">

                <div class="p-1 rounded-2">

                    @foreach (var article in Model.Latest.Take(5))
                    {
                        <partial name="_CardImageTopPartial" model="article" />
                    }
                </div>

            </div>
            <div class="col-lg-6 col-md-6 rounded-2">

                @foreach (var article in Model.Latest.Skip(5).Take(4))
                {
                    <partial name="_CardImageTopPartial" model="article" />
                }
            </div>

            <div class="col-lg-3 rounded-2">

                <div class="row gy-4 gx-4">

                    <div class="col-lg-12 col-sm-6">
                        <div class="card bg-image card shadow-1-strong"
                             style="background-image: url('https://images.pexels.com/photos/2449543/pexels-photo-2449543.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
                            <div class="card-body">
                                <vc:weather city="Linköping"></vc:weather>
                            </div>
                            <div class="card-footer">
                                Data from OpenWeatherMap
                            </div>
                        </div>
                    </div>

                    <div class="card col-lg-12 col-sm-6">
                        <div class="card-body">
                            <cache expires-after="TimeSpan.FromMinutes(60)">
                                <vc:stock symbol="AAPL"></vc:stock>
                            </cache>
                        </div>
                        <div class="card-footer">
                            <small>Stock data provided by Alpha Vantage</small>
                        </div>
                    </div>

                    <div class="col-lg-12 col-md-12" id="ElPrice">
                        <vc:el-price></vc:el-price>
                    </div>

                </div>

                <div class="mt-3">
                    <h4 class="text-danger">MORE LATEST NEWS</h4>
                    <hr />
                    <vc:latest-news-view></vc:latest-news-view>
                </div>

            </div>

        </div>
    </div>
    <hr />
    <div class="card mb-3 text-center" style="max-width: 100%; height= auto;">
        <h6>ADVERTISEMENT</h6>
        <div class="row g-0">
            <div class="col-md-8">
                <a href="https://www.english.metro.tokyo.lg.jp/" target="_blank" class="btn text-white btn-dark mx-2" aria-label="Advertisement">
                    <img src="https://tpc.googlesyndication.com/simgad/9815006595481215279" class="img-fluid rounded-start justify-content-center" alt="Avertisement">
                </a>

            </div>

        </div>
    </div>
    <hr />

    <div class="section2">
        <div class="row gy-4 justify-content-center">
            <div class="col-lg-3">
                @foreach (var article in Model.Latest.Skip(11).Take(3))
                {
                    <partial name="_CardWithoutImagePartial" model="article" />

                }
            </div>
            <div class="col-lg-9 p-1 rounded-2">

                <div class="row gy-4">
                    <div class="col-lg-12">
                        @foreach (var article in Model.Latest.Skip(15).Take(1))
                        {
                            <partial name="_CardImageLeftPartial" model="article" />

                        }
                    </div>

                    <div class="row row-cols-1 row-cols-md-3">

                        @foreach (var article in Model.Latest.Skip(16).Take(3))
                        {
                            <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
                                <partial name="_CardImageTopPartial" model="article" />
                            </div>

                        }

                    </div>

                </div>


            </div>
        </div>


    </div>


    <hr />
    <div class="card mb-3 text-center" style="max-width: 100%; height = auto;">
        <h6>ADVERTISEMENT</h6>
        <div class="row g-0">
            <div class="col-md-8">

                <a href="https://www.apollo.se/" target="_blank" class="btn text-white btn-dark mx-2" aria-label="Advertisement">
                    <img src="https://tpc.googlesyndication.com/simgad/13336854144519141404" class="img-fluid rounded-start justify-content-center" alt="Advertisement">
                </a>

            </div>

        </div>
    </div>
    <hr />
    <h4 class="p-1 mb-3 mt-3 text-danger"> MOST POPULAR NEWS</h4>
    <hr />


    <div class="section3">

        <div class="row gy-4 gx-4 justify-content-center">
            <div class="col-lg-8 p-1 rounded-2">

                <div class="row gy-4">
                    <div class="col-lg-12">
                        @foreach (var article in Model.MostPopular.Take(1))
                        {
                            
                                 <partial name="_CardImageLeftPartial" model="article" />
                           
                        }
                    </div>
                    <div class="row row-cols-1 row-cols-md-3">

                        @foreach (var article in Model.MostPopular.Skip(1).Take(3))
                        {
                            <div class="col-lg-4 col-md-6 mb-3 d-flex align-items-stretch">

                                <partial name="_CardImageTopPartial" model="article" />

                            </div>

                        }

                    </div>
                    
                </div>
               

                
            </div>

            <div class="col-lg-4">


                @foreach (var article in Model.MostPopular.Skip(4).Take(2))
                {
               
                        <partial name="_CardImageTopPartial" model="article" />

                }
            </div>

            <div class="row row-cols-1 row-cols-md-4">

                @foreach (var article in Model.MostPopular.Skip(6).Take(4))
                {
                    <div class="col-lg-3 col-md-6 d-flex align-items-stretch">

                        <partial name="_CardImageTopPartial" model="article" />

                    </div>


                }

            </div>
        </div>
    </div>


    <hr />
    <h4 class="p-1 mb-3 mt-3 text-danger">EDITOR'S CHOICE</h4>
    <hr />
    <div class="section4">
        <div class="row gy-4 gx-4 justify-content-center">
            <div class="col-md-12 p-1 rounded-2">
                @foreach (var article in Model.EditorChoice.Take(1))
                {
                    <partial name="_CardImageRightPartial" model="article" />

                }
            </div>
            <div class="row row-cols-1 row-cols-md-4">

                @foreach (var article in Model.EditorChoice.Skip(1).Take(4))
                {
                    <div class="col-lg-3 col-md-6 d-flex align-items-stretch">

                        <partial name="_CardImageTopPartial" model="article" />

                    </div>

                }



            </div>
            @* <hr />
            <h4 class="p-1 mb-3 mt-3 text-danger">MORE EDITOR'S CHOICE</h4>
            <hr /> *@
           @*  <div class="row row-cols-1 row-cols-md-6">
                @foreach (var article in Model.EditorChoice.Skip(5).Take(6))
                {
                    <div class="col-lg-2 mb-3 d-flex align-items-stretch">

                        <partial name="_CardWithoutImagePartial" model="article" />

                    </div>

                }
            </div> *@
            <div class="row row-cols-1 row-cols-md-4">

                @foreach (var article in Model.EditorChoice.Skip(11).Take(4))
                {
                    <div class="col-lg-3 col-md-6 d-flex align-items-stretch">

                        <partial name="_CardImageTopPartial" model="article" />

                    </div>

                }

            </div>

        </div>

       


    </div>
    

</div>

TeamFyraSidor/Views/Home/LanguageAI.cshtml
@using Azure.AI.TextAnalytics
@model DocumentSentiment

<h2>Sentiment Analysis</h2>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}
else if (ViewBag.Sentiment != null && ViewBag.ConfidenceScores != null)
{
    <div>
        <p><strong>Sentiment:</strong> @ViewBag.Sentiment</p>
        <p><strong>Confidence Scores:</strong></p>
        <ul>
            <li><strong>Positive:</strong> @ViewBag.ConfidenceScores.Positive</li>
            <li><strong>Neutral:</strong> @ViewBag.ConfidenceScores.Neutral</li>
            <li><strong>Negative:</strong> @ViewBag.ConfidenceScores.Negative</li>
        </ul>
    </div>
}
else
{
    <div class="alert alert-warning">No sentiment data available.</div>
}

<form method="post" action="@Url.Action("LanguageAI", "Home")">
    <textarea name="text" rows="4" cols="50" placeholder="Enter text for sentiment analysis"></textarea>
    <button type="submit">Analyze Sentiment</button>
</form>

TeamFyraSidor/Views/Home/Local.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "Local";
}

<div>
    <h4 class="mb-3 mt-5 text-danger">LOCAL NEWS</h4>
    <hr />

    <partial name="_CategoryPartial" model="@Model" />
</div>

TeamFyraSidor/Views/Home/Search.cshtml
@using Microsoft.AspNetCore.Identity;
@using TeamFyraSidor.Data;
@model IEnumerable<TeamFyraSidor.Models.ViewModels.ArticleCategoryLikedVM>;
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager;
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}
<form asp-action="Search" asp-controller="Home" method="get" class="d-flex" role="search">
    <input class="form-control me-2" name="searchString" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-dark" type="submit">Search</button>
</form>

<h2>Search Result</h2><br />

    @foreach (var article in Model)
    {
        <a asp-action="DisplayArticle" asp-controller="Article" asp-route-id="@article.Article.Id">
            <div class="row">
                <div class="col-3">
                <img src="@article.Article.ImageLink" class="card-img rounded-2" alt="@article.Article.Headline" width="260" height="180">
                </div>
                <div class="col-8 card">
                    <div class="card-body">
                    <h5 class="card-title">@article.Article.Headline</h5>
                    <p class="card-text">@article.Article.ContentSummary</p>
                    </div>
                    <div class="card-footer">
                    <span>@article.Article.DateStamp.ToShortDateString()</span> |
                    <span>@article.Article.Category!.Name</span> |
                    <span><i class="fa-regular fa-thumbs-up"></i>&nbsp;@article.Article.Likes</span> |
                    <span><i class="fa-regular fa-eye"></i>&nbsp;@article.Article.Views</span>
                    @if (article.Article.UpdateStamp > article.Article.DateStamp)
                        {
                        <span> | Updated: @article.Article.UpdateStamp</span>
                        }
                    </div>
                </div>
            </div>
        </a>
        <br />
    }

TeamFyraSidor/Views/Home/Sports.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "Sports";
}

<h4 class="mb-3 mt-5 text-danger">SPORTS NEWS</h4>
<hr />

<partial name="_CategoryPartial" model="@Model" />

TeamFyraSidor/Views/Home/Sweden.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "Sweden";
}

<h4 class="mb-3 mt-5 text-danger">SWEDEN NEWS</h4>
<hr />

<partial name="_CategoryPartial" model="@Model" />

TeamFyraSidor/Views/Home/Travel.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "Travel";
}

<h4 class="mb-3 mt-5 text-danger">TRAVEL NEWS</h4>
<hr />

<partial name="_CategoryPartial" model="@Model" />

TeamFyraSidor/Views/Home/World.cshtml
@model TeamFyraSidor.Models.ViewModels.CategoryPageVM
@{
    ViewData["Title"] = "World";
}

<h4 class="mb-3 mt-5 text-danger">WORLD NEWS</h4>
<hr />

<partial name="_CategoryPartial" model="@Model" />